public class Calculator {
    integer a=100;
    integer b=10;
    integer res;
    
    public void dosum(){
        res = a+b;
        System.debug('Sum = '+res);
    }
    
    public void dosub(){
        res = a-b;
        System.debug('Sub = '+res);
    }
    
    public void domul(){
        res = a+b;
        System.debug('mul = '+res);
    }
    
     public void dodiv(){
        res = a+b;
        System.debug('div = '+res);
    }

}